# Generated by Django 3.1.3 on 2021-01-02 14:26

import accounts.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busdetails',
            fields=[
                ('bus_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('bus_route', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=20)),
                ('bus_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.busdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=20)),
                ('bus_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.busdetails')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=250, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=10, unique=True)),
                ('Parent_Phone', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('Address_line', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Branch', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='active')),
                ('is_feepaid', models.BooleanField(default=False, verbose_name='active')),
                ('Pincode', models.TextField()),
                ('bus_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.busdetails')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
