# Generated by Django 3.1.3 on 2021-01-02 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210102_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bus_number',
        ),
        migrations.CreateModel(
            name='UserBusmapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.busdetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
