# Generated by Django 3.1.3 on 2021-01-03 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210102_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetails',
            name='Amount',
            field=models.CharField(default=3000, max_length=10),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('paid_amount', models.CharField(max_length=10)),
                ('bus_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.busdetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
